# FRONTEND SERVICE
# nginx trả về HTML đơn giản để phân biệt với api và admin
# Kiểm tra sau khi apply:
#   kubectl get pods -n ingress-lab -l app=frontend
#   kubectl get svc frontend-svc -n ingress-lab
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: ingress-lab
data:
  index.html: |
    <h1>FRONTEND</h1>
    <p>Bạn đang ở: / (root path)</p>
    <p>Service: frontend-svc</p>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ingress-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: app
        image: nginx:1.25.3
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "128Mi" }
        readinessProbe:
          httpGet: { path: /, port: 80 }
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: html
        configMap:
          name: frontend-html
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: ingress-lab
spec:
  selector:
    app: frontend           # phải khớp label trên Deployment Pods
  ports:
  - port: 80
    targetPort: 80
